print("Start loading libraries.....")
# Load libraries
# print("loading shiny")
library(shiny)
# print("loading shinyWidgets")
library(shinyWidgets)
# print("loading shinyjs")
library(shinyjs)
# print("loading Seurat")
library(Seurat)
# print("loading HDF5Array")
library(HDF5Array)
# print("loading dplyr")
library(dplyr)
# print("loading tidydr")
library(tidydr)
# print("loading tibble")
library(tibble)
# print("loading ggplot2")
library(ggplot2)
# print("loading patchwork")
library(patchwork)
# print("loading purrr")
library(purrr)
# print("loading ggpubr")
library(ggpubr)
# print("loading ComplexHeatmap")
library(ComplexHeatmap)
# print("loading circlize")
library(circlize)
# print("loading tidyverse")
library(tidyverse)
# print("loading ggh4x")
library(ggh4x)
# print("loading RColorBrewer")
library(RColorBrewer)
# print("loading glue")
library(glue)
# print("loading pool")
library(pool)
# print("loading furrr")
library(furrr)
# print("cognitoR")
# library(cognitoR)
library(plotly)
library(aws.s3)
library(paws.storage)
print("Finish libraries loading .....")

options(warn=-1)

# Load functions
source("code/sources/computeUMAP.R")
source("code/sources/computeBarPlot_CellType_Status.R")
source("code/sources/computeVln.R")
source("code/sources/computeHeatmap.R")
source("code/sources/computeStackBarPlot_Subject.R")
source("code/sources/computeFeaturePert.R")
source("code/sources/computeDotPlot.R")
source("code/sources/seurat_analysis_utilities.R")

# Determine the environment and load the appropriate .env file
env <- Sys.getenv("APP_ENV", unset = "local")
cat("env:", env, "\n")

shiny_port <- as.integer(Sys.getenv("SHINY_PORT", unset = "3838"))
shiny_host <- Sys.getenv("SHINY_HOST", unset = "0.0.0.0")

# Print to log to verify values
cat("SHINY_HOST:", shiny_host, "\n")
cat("SHINY_PORT:", shiny_port, "\n")

# Select the appropriate APP_DOMAIN based on the environment
app_domain <- Sys.getenv(paste0("APP_DOMAIN_", toupper(env)))
